version: '3'

services:
  # infrastructure
  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_DB: sivdev
      POSTGRES_USER: sivdev_user
      POSTGRES_PASSWORD: sivdev_pass
    ports:
      - "9432:5432"
  redis:
    image: redis:4.0-alpine

  # web app
  api:
    build:
      context: .
    command: ["gunicorn", "app:api", "-b", "0.0.0.0:7000", "--reload", "--timeout",  "100000"]
    environment:
      DATABASE_URI: postgresql://sivdev_user:sivdev_pass@db:5432/sivdev
      PYTHONPATH: .
    depends_on:
      - db
      - redis
      - worker
      - rq-dash
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "7000:7000"

  # task queue
  rq-dash:
    build:
      context: ./rq-dashboard/
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redis:6379
    ports:
      - "9181:9181"
    command: ["rq-dashboard"]
  worker:
    build:
      context: .
    command: ["python", "/app/scripts/worker.py"]
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - .:/app
