version: '3.4'

services:
  # infrastructure
  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_DB: sivdev
      POSTGRES_USER: sivdev_user
      POSTGRES_PASSWORD: sivdev_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    ports:
      - "9432:5432"
  redis:
    image: redis:4.0-alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli","ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  # web app
  api:
    build:
      context: .
    command: ["gunicorn", "app:api", "-b", "0.0.0.0:7000", "--reload", "--timeout",  "100000"]
    environment:
      API_URL: http://api:7000
      DATABASE_URI: postgresql://sivdev_user:sivdev_pass@db:5432/sivdev
      ELASTICSEARCH_URI: http://elasticsearch:9200
      GMAIL_ADDRESS: $GMAIL_ADDRESS
      GMAIL_APPLICATION_PASSWORD: $GMAIL_APPLICATION_PASSWORD
      MYPYPATH: .
      PYTHONPATH: .
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
      - worker
      - rq-dash
      - rq-scheduler
      - elasticsearch
      - kibana
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "7000:7000"

  # task queue
  rq-dash:
    build:
      context: ./scripts/rq-dashboard/
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    ports:
      - "9181:9181"
    command: ["rq-dashboard"]
  rq-scheduler:
    build:
      context: ./scripts/rq-scheduler/
    environment:
      RQ_REDIS_HOST: redis
      RQ_REDIS_PORT: 6379
    depends_on:
      - redis
    command: ["rqscheduler"]
  worker:
    build:
      context: .
    environment:
      GMAIL_ADDRESS: $GMAIL_ADDRESS
      GMAIL_APPLICATION_PASSWORD: $GMAIL_APPLICATION_PASSWORD
      REDIS_URL: redis://redis:6379
    command: ["python", "/app/start_worker.py"]
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  # elasticstack
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
